### ISSUE TITLE
Problem with inkscape 1.0

### ISSUE THREAD

**Issue by Dimdimtri** [JTechPhotonics/J-Tech-Photonics-Laser-Tool#17]
Hello everyone, I just installed inkscape 1.0, if I draw a rectangle the plugin works fine. However if I import an external svg it gives me this error and the file is completely wrong. 

The same file on inkscape 0.92 works fine, I had to install inkscape 1.0 on my imac 10.15.

thank you in advance for your help.

laser.py:928: DeprecationWarning: simpletransform.parseTransform -> Transform(str).matrix
  t = simpletransform.parseTransform(t)
laser.py:938: DeprecationWarning: simpletransform.applyTransformToPath -> Path(path).transform(mat)
  simpletransform.applyTransformToPath(trans, csp)
laser.py:295: DeprecationWarning: inkex.bezier.bezierlength -> Get length of bezier curve
  return bezmisc.bezierlength(bez, tolerance)

**Comment by topogigio** [comment]
Hi,
I have same problem with Hershey font.
Thanks

Very big and strange tracks are generated after error:

laser.py:928: DeprecationWarning: simpletransform.parseTransform -> Transform(str).matrix
  t = simpletransform.parseTransform(t)
laser.py:929: DeprecationWarning: simpletransform.composeTransform -> Transform(M1) * Transform(M2)
  trans = simpletransform.composeTransform(t, trans) if trans != [] else t
laser.py:938: DeprecationWarning: simpletransform.applyTransformToPath -> Path(path).transform(mat)
  simpletransform.applyTransformToPath(trans, csp)

**Comment by aspeteRakete** [comment]
<img width="846" alt="Screenshot 2020-12-31 at 12 05 32" src="https://user-images.githubusercontent.com/1003846/103407912-9beee380-4b60-11eb-8616-63b01ec0fab4.png">
It seems that the center point of the object is translated to x=0 y=document_height

**Comment by PadLex** [comment]
Should be fixed with the 2.0 release. Can you confirm?
