### ISSUE TITLE
Run script for selected paths

### ISSUE THREAD

**Issue by bigtree908** [JTechPhotonics/J-Tech-Photonics-Laser-Tool#18]
I'm unable to select or in some way isolate paths that I want to run the script on. This would be useful when you need to engrave one group of paths and cut another.

**Comment by PadLex** [comment]
Should be fixed with the 2.0 release. Can you confirm?

**Comment by bigtree908** [comment]
Doesn't seem to be working. Do I need to do something more than select the path then run the script?

**Comment by PadLex** [comment]
Ups, I should mention this in the tutorial. The plugin will ignore any hidden objects or layers. So just place everything you want to hide in one layer and hide it.

**Comment by PadLex** [comment]
Awesome!
