### ISSUE TITLE
Plugin not ignoring clipped paths

### ISSUE THREAD

**Issue by GilesMetcalf** [JTechPhotonics/J-Tech-Photonics-Laser-Tool#19]
I have noticed that the plugin does not ignore any paths clipped (and therefore not visible) in InkScape, and is still generating gcode for them, which then appear on the finished work. 

I am using version 2.2 of the plugin, version 0.92.4 InkScape, and version 2.7.12 of Python.

**Comment by GilesMetcalf** [comment]
Oops, sorry - I meant version 1.1 of the plugin...

**Comment by PadLex** [comment]
Should be fixed with the 2.0 release. Can you confirm?
