### ISSUE TITLE
Problems with Inkscape 1.0

### ISSUE THREAD

**Issue by bianchifan** [JTechPhotonics/J-Tech-Photonics-Laser-Tool#2]
Scenario 1: Windows 10 x64, Inkscape 1.0 portable freshly unzipped
SVG: Multilayer SVG, all layers unvisible but TWO! cutting layers

Result:
Several deprecation messages and a weird screen ouput in preview, the plug took use of some hided layers and created its own positions, 
![Win10](https://user-images.githubusercontent.com/17491743/84682234-a4b9f800-af35-11ea-9834-3cb8e7c81fe6.jpg)
scalings and proportions.

A little closer view with the shades of the two cutting layers "cut1" and "Cut Seg Lockout" within the DIN A4 frame
![win10-2](https://user-images.githubusercontent.com/17491743/84682626-33c71000-af36-11ea-82bc-4a4e46eb7ce8.jpg)
![win10-3](https://user-images.githubusercontent.com/17491743/84682950-bb148380-af36-11ea-9056-77b9b15e2865.jpg)

The generated gcode file includes 300kB Data.

Next try, same svg with all unvisible layers deleted:
![win10-4](https://user-images.githubusercontent.com/17491743/84682927-b18b1b80-af36-11ea-8c45-52dc71929f2a.jpg)
![win10-5](https://user-images.githubusercontent.com/17491743/84682974-c2d42800-af36-11ea-9e22-f9b52c9e0186.jpg)

Odd placement but correct scalings and dimensions, the generated gcode counts 8,6 kB ;)

Scenario 2 : Windows 7x32 within Virtualbox on Ubuntu Host(20.04), Inkscape 1.0 portable freshly unzipped
SVG: One layer with an outline for cutting, burning..
same screen results as with scenario 3

Scenario 3: Ubuntu 20.04 
deprecation warnings, wrong scaling, wrong placing
![Bildschirmfoto von 2020-06-13 10-49-07](https://user-images.githubusercontent.com/17491743/84685385-7db1f500-af3a-11ea-9e14-d1cea44ce0cc.jpg)
![Bildschirmfoto von 2020-06-13 10-47-17](https://user-images.githubusercontent.com/17491743/84685392-8276a900-af3a-11ea-83f6-57dfbe28898d.jpg)

While win7 gcode (scenario 3) eats 2.9 kB Ubuntu's gcode is a little smaller, 2.7 kB
Both files match in line numbers but differ in "G1" code lines..
![Bildschirmfoto von 2020-06-15 18-03-34](https://user-images.githubusercontent.com/17491743/84685844-38da8e00-af3b-11ea-9a11-f7c337e76c6e.jpg)

To compare:
With Inkscape 0.92.5/Ubuntu Studio 19.10 the screen output is correct (within borders, lines&arrows maybe a little big..) and the gcode eats only 2.5 K while tallying same lines but differing of course..
![Bildschirmfoto_2020-06-15_18-53-47](https://user-images.githubusercontent.com/17491743/84686508-5d833580-af3c-11ea-8599-deab02704af4.png)

![Bildschirmfoto von 2020-06-15 19-14-08](https://user-images.githubusercontent.com/17491743/84686594-8acfe380-af3c-11ea-8e0e-5928e47264a3.jpg)

**Comment by jithivk** [comment]
raceback (most recent call last):
  File "laser.py", line 78, in <module>
    from inkex.paths import CubicSuperPath  # noqa
ImportError: No module named paths
 this is the error what i have

**Comment by mountwebs** [comment]
I get some similar results to OPs. The extension mostly works fine, but when I tried to use it after applying Hershey text, I got the same script error as @bianchifan and the result in inkscape was a lot of huge displaced paths.

macOS 10.13, Inkscape 1.0.

**Comment by PadLex** [comment]
> raceback (most recent call last):
> File "laser.py", line 78, in
> from inkex.paths import CubicSuperPath # noqa
> ImportError: No module named paths
> this is the error what i have

Jithivk, check out this issue. [ImportError: No module named paths #3](https://github.com/JTechPhotonics/J-Tech-Photonics-Laser-Tool/issues/3)

**Comment by PadLex** [comment]
@bianchifan This is really weird. I'm not even sure how to start reproducing this bug. The output really shouldn't vary between operating systems. Are you sure you kept the same Inkscape version, extension version, and settings between experiments?

**Comment by PadLex** [comment]
In the meantime, could you share the SVG's which don't work? I can't work on this now but I'll try and reproduce your issue when I have a little time.

**Comment by bianchifan** [comment]
> 
 The output really shouldn't vary between operating systems. Are you sure you kept the same Inkscape version, extension version, and settings between experiments?

Ubuntu 20.02:  Official Inkscape 1.0

Windows 10 x64
Windowx 7 x32 (Modern IE) / Virtualbox :  Inscape 1.0 poertable from PortableApps
![InkscapePortable](https://user-images.githubusercontent.com/17491743/87406536-1e8ae300-c5c1-11ea-9dd8-455277761b41.jpg)
![laser extension](https://user-images.githubusercontent.com/17491743/87406547-2185d380-c5c1-11ea-941d-79918b048bbe.jpg)

Settings should be equal

**Comment by bianchifan** [comment]
> 
> 
> In the meantime, could you share the SVG's which don't work?

In the meantime the svgs had changed due to to varied placing and new objects.
I can share the actual version:

[Fox32_decals_Set_portrait.zip](https://github.com/JTechPhotonics/J-Tech-Photonics-Laser-Tool/files/4917757/Fox32_decals_Set_portrait.zip)
![Fox32-portrait](https://user-images.githubusercontent.com/17491743/87407897-0fa53000-c5c3-11ea-9c40-7ce416110cbe.jpg)

[Fox32_decals_Set_portrait_cut2.zip](https://github.com/JTechPhotonics/J-Tech-Photonics-Laser-Tool/files/4917766/Fox32_decals_Set_portrait_cut2.zip)
![Fox32-cut2](https://user-images.githubusercontent.com/17491743/87407945-2186d300-c5c3-11ea-8bed-1c196d5998a7.jpg)

**Comment by JuPrgn** [comment]
Hi,
I have same warning with fresh Inkscape 1.0 install and corresponding pluggin 1.0 beta (win7 64).
In my case the preview is very far from the original drawing : 
![image](https://user-images.githubusercontent.com/20264907/87452693-d04a0400-c601-11ea-892c-48b3782dac0b.png)

I had already reported this bug with this file to JTP with previous 0.92 extension.

The source file is a part from another complex SVG and I only extracted the part that make this bug happen : 
[drawing_initial.zip](https://github.com/JTechPhotonics/J-Tech-Photonics-Laser-Tool/files/4920053/drawing_initial.zip)
![image](https://user-images.githubusercontent.com/20264907/87452752-e48e0100-c601-11ea-86d0-84ce2b4222e7.png)

Please let me know if you need some more details.

**Comment by bianchifan** [comment]
> @bianchifan It would be nice if you could give it a try and share if you have similar issue with my SVG

1st.. Ubuntu 20.04 / Inkscape 1.0

does not run due to syntax error
![Bildschirmfoto von 2020-07-14 19-53-38](https://user-images.githubusercontent.com/17491743/87461691-0f328680-c60f-11ea-8717-b996194d8aa6.png)

2nd.. Win7 x32 / Inkscape 1.0 portable version (PortableApps) via Virtualbox
![VirtualBox_IE8 - Win7_14_07_2020_19_49_54](https://user-images.githubusercontent.com/17491743/87461858-4d2faa80-c60f-11ea-92e3-5b88287738e2.png)

**Comment by PabloSica** [comment]
Hello friends. I use your plugin for laser engraving in InkScape 1.0 on a Catalina MacOs. 
In this version of MacOs I cannot install 0.92, only 1.0 For some reason after updating the Operating System I can no longer use the plugin. When I generate the file for recording, I receive the following message: 
File "laser.py", line 51
    def bezierslopeatt ((((bx0, by0), (bx1, by1), (bx2, by2), (bx3, by3)), t):
                       ^
SyntaxError: invalid syntax

I appreciate if you can help me.
Congratulations on the great job.
Thank you.
Pablo Sica

**Comment by PadLex** [comment]
All of the above issues should be fixed in the latest release v1.1 patch. @bianchifan and everyone else, let me know if the problem has been resolved so I can close this issue.

**Comment by bianchifan** [comment]
quick test of v1.1 patch...
- actions within Ubuntu 20.04 and Win7-Virtualbox(Modern IE) are equal, scaling & positioning seems to be ok :)
- still no difference between hidden and visible layers - all layers are routed
- the preview shines very ,very big, still - not able to drive in detailed view
![VirtualBox_IE8 - Win7_28_07_2020_18_39_20](https://user-images.githubusercontent.com/17491743/88696668-d234bc80-d103-11ea-95e2-e96a1a6acef0.jpg)
![Bildschirmfoto von 2020-07-28 18-45-27](https://user-images.githubusercontent.com/17491743/88696678-d52fad00-d103-11ea-9342-91dafffdf99e.jpg)

PS:
only this should be routed
![Bildschirmfoto von 2020-07-28 18-58-11](https://user-images.githubusercontent.com/17491743/88697108-656df200-d104-11ea-999f-d4033f8ab6d9.jpg)

**Comment by PadLex** [comment]
Perfect, the scaling issues were the main problem here. The fact that hidden layers aren't ignored is the subject of a different issue so I'll close this one.
