### ISSUE TITLE
Scaling Issue

### ISSUE THREAD

**Issue by jh8man** [JTechPhotonics/J-Tech-Photonics-Laser-Tool#23]
Hi, 
I have noticed some strange errors with the laser.py app.
Mac OS Big Sur
Inkscape 1.0.1
Jtech photonics Laser tool 1.1 patch

The exported Gcode is not scaled correctly. 
I did the following test.
Made a 6" square, set 1" from border in X and Y.

As you can see, the Gcode output is not as expected; it results in a 1.69in square.
Additionally, the app places a "5,0,0" showing me, I think, where the app locates (x5,y0,z0).

units in drawing and jtech app are "in"

what am I doing incorrectly?

Thank you
James
![inkscape_jtech_Laser_scaling_error](https://user-images.githubusercontent.com/50158245/104846953-e54e6b00-58a2-11eb-9955-1fcb127983ad.jpg)

**Comment by PadLex** [comment]
Should be fixed with the 2.0 release. Can you confirm?
