### ISSUE TITLE
Filling path of an object

### ISSUE THREAD

**Issue by tommy3001** [JTechPhotonics/J-Tech-Photonics-Laser-Tool#29]
Nice Plugin. 
JTP-Laser-Tool_v1.1-beta is working well with Inkscape 1.0.2:
Question:
How can I fill the content of a path if it is obviously colored?  For example for a yin yang logo (black / white area).

It is a possible feature for the plug in, or can it be handled by inkscape?

**Comment by nineff** [comment]
you can use some fill-methods to convert the area into paths. There exist several options for that, e.g. a hatch fill or a Hilbert-curve etc.
have a look at the https://github.com/KnoxMakers/KM-Laser extensions.

**Comment by tommy3001** [comment]
The extension works great for me. "Hatch Fill" is doing the job. Thanks!
