### ISSUE TITLE
Behaviour of path_depth 

### ISSUE THREAD

**Issue by tommy3001** [JTechPhotonics/J-Tech-Photonics-Laser-Tool#30]
Hallo. 
I tried the blending edge JTP-Laser-Tool_v2.0-beta3.zip today. 
I like the integration of SvgToGcode. 

But I am not lucky with the meaning of _path_depth_. It is not working in the for me expected way. In SvgToGcode, it is only added when  _passes_ is higher than 1.   It adds then after a complete svg graph cycle G1 Z-path_depth.  But that is an issue more related to SvgToGcode.

**Comment by tommy3001** [comment]
Never mind. The post was mainly based on a misinterpretation of the code.

**Comment by PadLex** [comment]
Should be fixed with the 2.0 release. Can you confirm?
