### ISSUE TITLE
Options missing for setting Z-Axis

### ISSUE THREAD

**Issue by marcvs** [JTechPhotonics/J-Tech-Photonics-Laser-Tool#41]
This is important for setting the laser cutter to the correct height from the gcode.

Also, the laser does not move "back home" after it's done.

**Comment by PadLex** [comment]
Addressed in the [latest commit](https://github.com/JTechPhotonics/J-Tech-Photonics-Laser-Tool/commit/0627295a6499b15f341c6cf8104f8a6d62e6fa90).
