### ISSUE TITLE
Negative offset values?

### ISSUE THREAD

**Issue by Mazvy** [JTechPhotonics/J-Tech-Photonics-Laser-Tool#45]
I'm using this plugin to add plotter functionality to my 3D printer, as such the offsets are weird as my pen and vinyl cutter are in awkward positions.

By manually moving all axis, my 0,0 for my pen is X: -3mm, Y: 80mm, but I cannot put in negative offset values for X. 

Hopefully this is an easy fix?

**Comment by PadLex** [comment]
Ups. I just updated the binaries to fix that.
