### ISSUE TITLE
Cannot engrave (just cutting) with grbl and inkscape

### ISSUE THREAD

**Issue by dekiakbar** [JTechPhotonics/J-Tech-Photonics-Laser-Tool#49]
I have build A laser CNC running arduino with :
GRBL 1.1h
Inkscape v1.0.2
J-Tech-Photonics-Laser-Tool v2.4

BTW I use archlinux (I think this is not OS issue)
everithyng is good but how to do engrave using this plugin ? I have read the doc here but still cannot engrave https://jtechphotonics.com/?page_id=2012

**Comment by PadLex** [comment]
Did something go wrong or is process unclear? I've been putting off working on the docs, I think they're a little confusing.

**Comment by dekiakbar** [comment]
yeah the docs id little confusing, I think it must be updated, when I engrave a (i.e star image), only the outline of the star image is engraved. the plugin generated gcode without filling the area of star image. can you reproduce it on your own machine ?

**Comment by PadLex** [comment]
Yep. This extension specifically converts svg paths to gcode for engraving and cutting. In other words, it draws lines. To fill in an area I recommend you look for png/jpeg to gcode engraving projects.

**Comment by dekiakbar** [comment]
aah okay thanks @PadLex , I will close this issue 👍🏻
