### ISSUE TITLE
Offset in y axis

### ISSUE THREAD

**Issue by agryson** [JTechPhotonics/J-Tech-Photonics-Laser-Tool#50]
Using Inkscape 1.1 I get a warning while running about transforms (maybe related) and upon generation notice that the gcode is offset downwards by about a centimetre.

The points in this screen shot should be at each corner of the canvas for example.

![image](https://user-images.githubusercontent.com/1445853/122645442-e66a1980-d11a-11eb-88e8-d6fd0aac618b.png)

**Comment by agryson** [comment]
The offset is precisely 11.25mm. I can work around this by manually remembering to offset prior to gcoding, but naturally a proper fix (or info on what I may be doing wrong?) would be helpful.

**Comment by PadLex** [comment]
Welcome!

It looks like you're using an outdated version of the extension. Try installing the latest 2.x version ;)

**Comment by agryson** [comment]
🤦 Thank you, you're right, I originally downloaded from https://jtechphotonics.com/?page_id=1980 so was on V1.1_beta.
Jus ttested and it works _perfectly_.
Apologies and thanks.
