### ISSUE TITLE
ModuleNotFoundError: No module named 'svg_to_gcode'

### ISSUE THREAD

**Issue by dfgianni** [JTechPhotonics/J-Tech-Photonics-Laser-Tool#56]
hi, i have this error with the J-Tech-Photonics-Laser-Tool. it is installed on a 1.0.2-2 inkskape version. how i can resolve this problem?

**Comment by dfgianni** [comment]
the J-Tech-Photonics-Laser-Tool version is 2.4. many thanks

**Comment by PadLex** [comment]
You could downgrade to a previous version of the extension or install the latest version of Inkscape. If neither works make sure to post the error so we can help you better.

**Comment by dfgianni** [comment]
upgradeded inkscape to the last version 1.1 but i have always the same problem in attached:

Traceback (most recent call last):
  File "laser.py", line 7, in <module>
    from svg_to_gcode.svg_parser import parse_root, Transformation, debug_methods
ModuleNotFoundError: No module named 'svg_to_gcode'

**Comment by PadLex** [comment]
The error is saying that the svg_to_gcode folder isn't in the same directory as the laser.py file. When you install the extension you need to make sure you copy over both the svg_to_gcode folder and the laser.py/laser.inx files.

**Comment by dfgianni** [comment]
oh, i'm sorry. wich is the download file of the svg_to_gcode? can you help to to install it correct? it seems that i need to install it with pip or i can just copy files?

**Comment by dfgianni** [comment]
![image](https://user-images.githubusercontent.com/64104025/129901058-89eca829-b6f5-4714-995a-380e5e42e2cb.png)

**Comment by superfluent** [comment]
For n00bs like me:
- Make sure you got Python installed and added tp PATH
- start cmd
- cd to location of setup.py
- execute "setup.py install"
(Installs successfully)

Unluciky I remain with the following errors: 
![JTechError](https://user-images.githubusercontent.com/9412526/147396052-5bd4d5b4-b1da-47d8-b373-fcb8077a93e9.png)

**Comment by PadLex** [comment]
How odd, if it isn't too late, could you post a picture of your directory structure after installing the library? It's very important that the laser.py and laser.inx files be in the same location as the svg_to_gcode folder.

**Comment by andraisr** [comment]
Thanks for this info. I surmise that the contents of the svgtogcode zip file be saved into the laser folder.
