### ISSUE TITLE
Laser tool not showing up in Inkscape v1.1 as an Extension.

### ISSUE THREAD

**Issue by StevenMarston** [JTechPhotonics/J-Tech-Photonics-Laser-Tool#58]
The path seems to have changed for the location of the Inkscape extensions.
New is "C:\Program Files\Inkscape\share\inkscape\extensions\"
Previously: "C:\Program Files\Inkscape\share\extensions".

Not sure if it affects it showing up since the location for placing the file is different.

I do see in V1.1 that an extension called "Gcodetools" that's not related.

**Comment by StevenMarston** [comment]
Disregard... I found it as "Generate Laser GCode" **then the flyout shows J-Tech**.  Was looking for it to be titled "J-Tech".

**Comment by PadLex** [comment]
Glad it works now 👍
