### ISSUE TITLE
Add setting for dynamic output filename

### ISSUE THREAD

**Issue by peschmae** [JTechPhotonics/J-Tech-Photonics-Laser-Tool#61]
Right now, it's not possible to just reuse the filename of the open SVG as filename for the gcode file.

Introducing a checkbox that allows a 'dynamic' name (eg. just strip the .svg from the open document, and append .gcode), would be really nice.

I've hacked something together already for a use case I had, and could contribute this feature. I would still need to do some error handling in case the open document wasn't saved before and `self.document_path()` isn't properly set.
In that case I would propose to just use the default `output.gcode` name.

**Comment by PadLex** [comment]
That sounds like an awesome feature. Feel free to create a pull request whenever you feel satisfied with your implementation.
