### ISSUE TITLE
Traceback Error (No Gcode Generated) TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType

### ISSUE THREAD

**Issue by Liizam** [JTechPhotonics/J-Tech-Photonics-Laser-Tool#76]
Help troubleshoot this error. I used to b able to run J Tech Tool. 

MacOS Sierra (10.12.6) 
Inkscape: 1.1.2
JTech Tool: v2.4 (downloaded June 27, 2022)  

**-------------- error: no gcode is generated -----------------**

Traceback (most recent call last):
  File "laser.py", line 290, in <module>
    effect.run()
  File "/Applications/Inkscape.app/Contents/Resources/share/inkscape/extensions/inkex/base.py", line 131, in run
    self.save_raw(self.effect())
  File "laser.py", line 63, in effect
    if os.path.isfile(self.options.header_path):
  File "/Applications/Inkscape.app/Contents/Frameworks/Python.framework/Versions/3.8/Resources/Python.app/Contents/MacOS/../../../../lib/python3.8/genericpath.py", line 30, in isfile
    st = os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType

**Comment by Liizam** [comment]
The Inkscape extension folder "laser" should contain the following files: 

- svg_to_gcode folder: https://github.com/PadLex/SvgToGcode
- laser.inx
- laser.py 

Now I can generate gcode but the scaling is severely off.

**Comment by phantomfsoc** [comment]
I have all those files in the extensions folder.
Didn't work

**Comment by phantomfsoc** [comment]
Actually with Inkscape 1.2 I'm not exactly sure where the plugin goes.
If I put the Laser folder in C:\Program Files\Inkscape\share\inkscape\extensions\
I see the Laser Tool Plug-In in the list of extensions in the program but it won't load.

I then read that plugins for this version go in C:\Users\(username)\AppData\Roaming\inkscape\extensions\

When I put the laser folder in there the same thing happens.

If I put the laser folder in both places, then I get duplicates in the Extension list but it opens it and I can use it until I try to Apply to create the gCode, and then my above issue happens.

What am I doing wrong?

**Comment by Liizam** [comment]
@phantomfsoc - I'm on a Mac. To see the correct folder, I go to Inkscape -> Preference -> System. I open the folder for "User Extensions" to grab the folder location. 
In the folder: "user extensions", I make one called laser. I paste the files mentioned in issue #76 there. 
Not sure where you are pasting them, but I would delete everything and start from scratch. I'm also using older Inkscape because my OS doesn't support the latest Inkscape.

**Comment by kurtpart** [comment]
hi, tnx for help but extension v2.4 comes as a folder named "laser" and i tried adding as folder, one by one etc. not working...
